language: node_js
after_success: npm run coverage && cat ./coverage/lcov.info | coveralls
script:
  - npm run test-node
  - npm run test-262
  - if [[ $(node --version) == v6* ]] ; then npm run test-browser; fi
node_js:
  - "0.10"
  - "0.12"
  - 4
  - 6
matrix:
  fast_finish: true
sudo: false
