language: node_js
after_success: npm run coverage && cat ./coverage/lcov.info | coveralls
before_install:
  # These packages cannot be installed in legacy versions of Node.js. Because
  # they are only needed to verify correctness in a browser-like environment,
  # they can be removed (and the tests skipped) without effecting coverage.
  - if [[ $(node --version) != v10* ]] ; then
      node scripts/remove-dev-dependencies.js puppeteer;
    fi
script:
  - npm run pretest
  - npm run $CMD
cache:
  npm: false
matrix:
  include:
    - node_js: "0.10"
      env: CMD=test-node
    - node_js: "0.12"
      env: CMD=test-node
    - node_js: 4
      env: CMD=test-node
    - node_js: 6
      env: CMD=test-node
    - node_js: 8
      env: CMD=test-node
    - node_js: 10
      env: CMD=test-node
    - node_js: 10
      env: CMD=test-262
    - node_js: 10
      env: CMD=test-browser
    - node_js: 10
      env: CMD=test-website
  fast_finish: true
sudo: false
