version: "{build}"

clone_depth: 10

environment:
  matrix:
    - nodejs_version: 0.10
    - nodejs_version: 0.12
    - nodejs_version: 4
    - nodejs_version: 6

install:
  - ps: Install-Product node $env:nodejs_version
  - git submodule update --init --recursive
  - npm install

build: off

test_script:
  - node --version && npm --version
  - npm run test-node
  - if "%nodejs_version%" == "6" npm run test-browser
  - if "%nodejs_version%" == "6" npm run test-262

cache:
  - node_modules            # local npm modules

matrix:
  fast_finish: true
